// <auto-generated />
using System;
using Kairos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace Kairos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KairosDbContext))]
    [Migration("20260921005045_AddCategories")]
    partial class AddCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kairos.Domain.Entities.Address", b =>
                {
                    b.Property<long>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AddressId"));

                    b.Property<byte>("AddressTypeId")
                        .HasColumnType("tinyint");

                    b.Property<string>("ApartmentUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("AddressId");

                    b.HasIndex("AddressTypeId");

                    b.HasIndex("UserId", "AddressTypeId")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Kairos.Domain.Entities.AddressType", b =>
                {
                    b.Property<byte>("AddressTypeId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressTypeId");

                    b.ToTable("AddressTypes");

                    b.HasData(
                        new
                        {
                            AddressTypeId = (byte)1,
                            Name = "Primary"
                        },
                        new
                        {
                            AddressTypeId = (byte)2,
                            Name = "Secondary"
                        },
                        new
                        {
                            AddressTypeId = (byte)3,
                            Name = "Tertiary"
                        });
                });

            modelBuilder.Entity("Kairos.Domain.Entities.Category", b =>
                {
                    b.Property<byte>("CategoryId")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = (byte)1,
                            IsActive = true,
                            Name = "Dresses",
                            Slug = "womens-dresses"
                        },
                        new
                        {
                            CategoryId = (byte)2,
                            IsActive = true,
                            Name = "Tops",
                            Slug = "tops"
                        },
                        new
                        {
                            CategoryId = (byte)3,
                            IsActive = true,
                            Name = "Women's Shoes",
                            Slug = "womens-shoes"
                        },
                        new
                        {
                            CategoryId = (byte)4,
                            IsActive = true,
                            Name = "Bags",
                            Slug = "womens-bags"
                        },
                        new
                        {
                            CategoryId = (byte)5,
                            IsActive = true,
                            Name = "Jewellery",
                            Slug = "womens-jewellery"
                        },
                        new
                        {
                            CategoryId = (byte)6,
                            IsActive = true,
                            Name = "Sunglasses",
                            Slug = "sunglasses"
                        },
                        new
                        {
                            CategoryId = (byte)7,
                            IsActive = true,
                            Name = "Men's Shirts",
                            Slug = "mens-shirts"
                        },
                        new
                        {
                            CategoryId = (byte)8,
                            IsActive = true,
                            Name = "Men's Shoes",
                            Slug = "mens-shoes"
                        },
                        new
                        {
                            CategoryId = (byte)9,
                            IsActive = true,
                            Name = "Watches",
                            Slug = "mens-watches"
                        });
                });

            modelBuilder.Entity("Kairos.Domain.Entities.PasswordHistoryEntry", b =>
                {
                    b.Property<long>("PasswordHistoryEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PasswordHistoryEntryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("PasswordHistoryEntryId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("PasswordHistoryEntries");
                });

            modelBuilder.Entity("Kairos.Domain.Entities.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductId"));

                    b.Property<byte>("CategoryId")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<long?>("SaleId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SaleId");

                    b.HasIndex("StoreId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1L,
                            CategoryId = (byte)1,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 10,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 129.99m,
                            Rating = 3.6400000000000001,
                            SalePrice = 116.99m,
                            StoreId = 1L,
                            Title = "Black Women's Gown"
                        },
                        new
                        {
                            ProductId = 2L,
                            CategoryId = (byte)1,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 16,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 89.99m,
                            Rating = 3.0499999999999998,
                            SalePrice = 75.59m,
                            StoreId = 1L,
                            Title = "Corset Leather With Skirt"
                        },
                        new
                        {
                            ProductId = 3L,
                            CategoryId = (byte)1,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 15,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 79.99m,
                            Rating = 4.5199999999999996,
                            SalePrice = 67.99m,
                            StoreId = 1L,
                            Title = "Corset With Black Skirt"
                        },
                        new
                        {
                            ProductId = 4L,
                            CategoryId = (byte)1,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 18,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 49.99m,
                            Rating = 4.8799999999999999,
                            SalePrice = 40.99m,
                            StoreId = 1L,
                            Title = "Dress Pea"
                        },
                        new
                        {
                            ProductId = 5L,
                            CategoryId = (byte)1,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 19,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 179.99m,
                            Rating = 4.4800000000000004,
                            SalePrice = 145.79m,
                            StoreId = 1L,
                            Title = "Marni Red & Black Suit"
                        },
                        new
                        {
                            ProductId = 6L,
                            CategoryId = (byte)2,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 12,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 29.99m,
                            Rating = 4.1699999999999999,
                            SalePrice = 26.39m,
                            StoreId = 1L,
                            Title = "Blue Frock"
                        },
                        new
                        {
                            ProductId = 7L,
                            CategoryId = (byte)2,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 19,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 19.99m,
                            Rating = 4.7699999999999996,
                            SalePrice = 16.19m,
                            StoreId = 1L,
                            Title = "Girl Summer Dress"
                        },
                        new
                        {
                            ProductId = 8L,
                            CategoryId = (byte)2,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 14,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/tops/gray-dress/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 34.99m,
                            Rating = 2.7200000000000002,
                            SalePrice = 30.09m,
                            StoreId = 1L,
                            Title = "Gray Dress"
                        },
                        new
                        {
                            ProductId = 9L,
                            CategoryId = (byte)2,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 13,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/tops/short-frock/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 24.99m,
                            Rating = 3.23,
                            SalePrice = 21.74m,
                            StoreId = 1L,
                            Title = "Short Frock"
                        },
                        new
                        {
                            ProductId = 10L,
                            CategoryId = (byte)2,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 13,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/tops/tartan-dress/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 39.99m,
                            Rating = 4.0499999999999998,
                            SalePrice = 34.79m,
                            StoreId = 1L,
                            Title = "Tartan Dress"
                        },
                        new
                        {
                            ProductId = 11L,
                            CategoryId = (byte)3,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 3,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 19.99m,
                            Rating = 2.5299999999999998,
                            SalePrice = 19.39m,
                            StoreId = 1L,
                            Title = "Black & Brown Slipper"
                        },
                        new
                        {
                            ProductId = 12L,
                            CategoryId = (byte)3,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 3,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/womens-shoes/calvin-klein-heel-shoes/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 79.99m,
                            Rating = 4.9199999999999999,
                            SalePrice = 77.59m,
                            StoreId = 1L,
                            Title = "Calvin Klein Heel Shoes"
                        },
                        new
                        {
                            ProductId = 13L,
                            CategoryId = (byte)3,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 14,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/womens-shoes/golden-shoes-woman/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 49.99m,
                            Rating = 3.2599999999999998,
                            SalePrice = 42.99m,
                            StoreId = 1L,
                            Title = "Golden Shoes Woman"
                        },
                        new
                        {
                            ProductId = 14L,
                            CategoryId = (byte)3,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 14,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/womens-shoes/pampi-shoes/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 29.99m,
                            Rating = 3.0499999999999998,
                            SalePrice = 25.79m,
                            StoreId = 1L,
                            Title = "Pampi Shoes"
                        },
                        new
                        {
                            ProductId = 15L,
                            CategoryId = (byte)3,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 18,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/womens-shoes/red-shoes/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 34.99m,
                            Rating = 3.25,
                            SalePrice = 28.69m,
                            StoreId = 1L,
                            Title = "Red Shoes"
                        },
                        new
                        {
                            ProductId = 16L,
                            CategoryId = (byte)4,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 18,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/womens-bags/blue-women's-handbag/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 49.99m,
                            Rating = 2.9199999999999999,
                            SalePrice = 40.99m,
                            StoreId = 1L,
                            Title = "Blue Women's Handbag"
                        },
                        new
                        {
                            ProductId = 17L,
                            CategoryId = (byte)4,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 4,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/womens-bags/heshe-women's-leather-bag/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 129.99m,
                            Rating = 4.9199999999999999,
                            SalePrice = 124.79m,
                            StoreId = 1L,
                            Title = "Heshe Women's Leather Bag"
                        },
                        new
                        {
                            ProductId = 18L,
                            CategoryId = (byte)4,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 14,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/womens-bags/prada-women-bag/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 599.99m,
                            Rating = 2.71,
                            SalePrice = 515.99m,
                            StoreId = 1L,
                            Title = "Prada Women Bag"
                        },
                        new
                        {
                            ProductId = 19L,
                            CategoryId = (byte)4,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 15,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/womens-bags/white-faux-leather-backpack/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 39.99m,
                            Rating = 3.3599999999999999,
                            SalePrice = 33.99m,
                            StoreId = 1L,
                            Title = "White Faux Leather Backpack"
                        },
                        new
                        {
                            ProductId = 20L,
                            CategoryId = (byte)4,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 12,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/womens-bags/women-handbag-black/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 59.99m,
                            Rating = 2.8900000000000001,
                            SalePrice = 52.79m,
                            StoreId = 1L,
                            Title = "Women Handbag Black"
                        },
                        new
                        {
                            ProductId = 21L,
                            CategoryId = (byte)5,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 15,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/womens-jewellery/green-crystal-earring/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 29.99m,
                            Rating = 3.96,
                            SalePrice = 25.49m,
                            StoreId = 1L,
                            Title = "Green Crystal Earring"
                        },
                        new
                        {
                            ProductId = 22L,
                            CategoryId = (byte)5,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 15,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/womens-jewellery/green-oval-earring/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 24.99m,
                            Rating = 3.5699999999999998,
                            SalePrice = 21.24m,
                            StoreId = 1L,
                            Title = "Green Oval Earring"
                        },
                        new
                        {
                            ProductId = 23L,
                            CategoryId = (byte)5,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 1,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/womens-jewellery/tropical-earring/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 19.99m,
                            Rating = 4.4000000000000004,
                            SalePrice = 19.79m,
                            StoreId = 1L,
                            Title = "Tropical Earring"
                        },
                        new
                        {
                            ProductId = 24L,
                            CategoryId = (byte)6,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 5,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/sunglasses/black-sun-glasses/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 29.99m,
                            Rating = 4.4100000000000001,
                            SalePrice = 28.49m,
                            StoreId = 1L,
                            Title = "Black Sun Glasses"
                        },
                        new
                        {
                            ProductId = 25L,
                            CategoryId = (byte)6,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 5,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 24.99m,
                            Rating = 3.8599999999999999,
                            SalePrice = 23.74m,
                            StoreId = 1L,
                            Title = "Classic Sun Glasses"
                        },
                        new
                        {
                            ProductId = 26L,
                            CategoryId = (byte)6,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 1,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/sunglasses/green-and-black-glasses/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 34.99m,
                            Rating = 4.5499999999999998,
                            SalePrice = 34.64m,
                            StoreId = 1L,
                            Title = "Green and Black Glasses"
                        },
                        new
                        {
                            ProductId = 27L,
                            CategoryId = (byte)6,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 11,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 19.99m,
                            Rating = 2.79,
                            SalePrice = 17.79m,
                            StoreId = 1L,
                            Title = "Party Glasses"
                        },
                        new
                        {
                            ProductId = 28L,
                            CategoryId = (byte)6,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 2,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/sunglasses/sunglasses/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 22.99m,
                            Rating = 3.02,
                            SalePrice = 22.53m,
                            StoreId = 1L,
                            Title = "Sunglasses"
                        },
                        new
                        {
                            ProductId = 29L,
                            CategoryId = (byte)7,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 15,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 29.99m,
                            Rating = 3.6400000000000001,
                            SalePrice = 25.49m,
                            StoreId = 1L,
                            Title = "Blue & Black Check Shirt"
                        },
                        new
                        {
                            ProductId = 30L,
                            CategoryId = (byte)7,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 1,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 24.99m,
                            Rating = 3.1800000000000002,
                            SalePrice = 24.74m,
                            StoreId = 1L,
                            Title = "Gigabyte Aorus Men Tshirt"
                        },
                        new
                        {
                            ProductId = 31L,
                            CategoryId = (byte)7,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 20,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 34.99m,
                            Rating = 3.46,
                            SalePrice = 27.99m,
                            StoreId = 1L,
                            Title = "Man Plaid Shirt"
                        },
                        new
                        {
                            ProductId = 32L,
                            CategoryId = (byte)7,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 7,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 19.99m,
                            Rating = 2.8999999999999999,
                            SalePrice = 18.59m,
                            StoreId = 1L,
                            Title = "Man Short Sleeve Shirt"
                        },
                        new
                        {
                            ProductId = 33L,
                            CategoryId = (byte)7,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 11,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 27.99m,
                            Rating = 2.7200000000000002,
                            SalePrice = 24.91m,
                            StoreId = 1L,
                            Title = "Men Check Shirt"
                        },
                        new
                        {
                            ProductId = 34L,
                            CategoryId = (byte)8,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 4,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 149.99m,
                            Rating = 4.7699999999999996,
                            SalePrice = 143.99m,
                            StoreId = 1L,
                            Title = "Nike Air Jordan 1 Red And Black"
                        },
                        new
                        {
                            ProductId = 35L,
                            CategoryId = (byte)8,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 18,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 79.99m,
                            Rating = 3.8799999999999999,
                            SalePrice = 65.59m,
                            StoreId = 1L,
                            Title = "Nike Baseball Cleats"
                        },
                        new
                        {
                            ProductId = 36L,
                            CategoryId = (byte)8,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 4,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 89.99m,
                            Rating = 4.9000000000000004,
                            SalePrice = 86.39m,
                            StoreId = 1L,
                            Title = "Puma Future Rider Trainers"
                        },
                        new
                        {
                            ProductId = 37L,
                            CategoryId = (byte)8,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 5,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 119.99m,
                            Rating = 4.7699999999999996,
                            SalePrice = 113.99m,
                            StoreId = 1L,
                            Title = "Sports Sneakers Off White & Red"
                        },
                        new
                        {
                            ProductId = 38L,
                            CategoryId = (byte)8,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 109.99m,
                            Rating = 4.6900000000000004,
                            StoreId = 1L,
                            Title = "Sports Sneakers Off White Red"
                        },
                        new
                        {
                            ProductId = 39L,
                            CategoryId = (byte)9,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 6,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mens-watches/brown-leather-belt-watch/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 89.99m,
                            Rating = 4.1900000000000004,
                            SalePrice = 84.59m,
                            StoreId = 1L,
                            Title = "Brown Leather Belt Watch"
                        },
                        new
                        {
                            ProductId = 40L,
                            CategoryId = (byte)9,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 17,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mens-watches/longines-master-collection/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 1499.99m,
                            Rating = 3.8700000000000001,
                            SalePrice = 1244.99m,
                            StoreId = 1L,
                            Title = "Longines Master Collection"
                        },
                        new
                        {
                            ProductId = 41L,
                            CategoryId = (byte)9,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 9,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-date-black-dial/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 8999.99m,
                            Rating = 4.9699999999999998,
                            SalePrice = 8189.99m,
                            StoreId = 1L,
                            Title = "Rolex Cellini Date Black Dial"
                        },
                        new
                        {
                            ProductId = 42L,
                            CategoryId = (byte)9,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 18,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-moonphase/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 12999.99m,
                            Rating = 2.5800000000000001,
                            SalePrice = 10659.99m,
                            StoreId = 1L,
                            Title = "Rolex Cellini Moonphase"
                        },
                        new
                        {
                            ProductId = 43L,
                            CategoryId = (byte)9,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 4,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mens-watches/rolex-datejust/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 10999.99m,
                            Rating = 3.6600000000000001,
                            SalePrice = 10559.99m,
                            StoreId = 1L,
                            Title = "Rolex Datejust"
                        },
                        new
                        {
                            ProductId = 44L,
                            CategoryId = (byte)9,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 5,
                            ImageUrl = "https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/thumbnail.webp",
                            IsActive = true,
                            OriginalPrice = 13999.99m,
                            Rating = 2.6899999999999999,
                            SalePrice = 13299.99m,
                            StoreId = 1L,
                            Title = "Rolex Submariner Watch"
                        });
                });

            modelBuilder.Entity("Kairos.Domain.Entities.Sale", b =>
                {
                    b.Property<long>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SaleId"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.HasKey("SaleId");

                    b.HasIndex("StoreId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Kairos.Domain.Entities.Store", b =>
                {
                    b.Property<long>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StoreId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("OwnerUserId")
                        .HasColumnType("bigint");

                    b.HasKey("StoreId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            StoreId = 1L,
                            City = "Johannesburg",
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Kairos Demo Store"
                        });
                });

            modelBuilder.Entity("Kairos.Domain.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneVerified")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Kairos.Domain.Entities.Address", b =>
                {
                    b.HasOne("Kairos.Domain.Entities.AddressType", "AddressType")
                        .WithMany("Addresses")
                        .HasForeignKey("AddressTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kairos.Domain.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddressType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kairos.Domain.Entities.PasswordHistoryEntry", b =>
                {
                    b.HasOne("Kairos.Domain.Entities.User", "User")
                        .WithMany("PasswordHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kairos.Domain.Entities.Product", b =>
                {
                    b.HasOne("Kairos.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kairos.Domain.Entities.Sale", "Sale")
                        .WithMany("Products")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kairos.Domain.Entities.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Sale");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Kairos.Domain.Entities.Sale", b =>
                {
                    b.HasOne("Kairos.Domain.Entities.Store", "Store")
                        .WithMany("Sales")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Kairos.Domain.Entities.Store", b =>
                {
                    b.HasOne("Kairos.Domain.Entities.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Kairos.Domain.Entities.AddressType", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Kairos.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Kairos.Domain.Entities.Sale", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Kairos.Domain.Entities.Store", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Kairos.Domain.Entities.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("PasswordHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
